name = "byjohann-link"
main = "./.output/server/index.mjs"
# Disable `*.workers.dev` subdomain
workers_dev = false
compatibility_date = "2023-06-13"

kv_namespaces = [
  { binding = "__BYJOHANN_LINK", id = "c80ecbb77b504762998f1286483c1230" }
]

[site]
bucket = ".output/public"
