name = "linktree"
main = "./.output/server/index.mjs"
# Disable `*.workers.dev` subdomain
workers_dev = false
compatibility_date = "2023-06-13"

kv_namespaces = [
  { binding = "__LINKTREE", id = "linktree" }
]

[site]
bucket = ".output/public"
