name = "byjohann-link"
pages_build_output_dir = "./dist"

compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "KV_BINDING", id = "f52afe050756444b8c2ac005f10afcb9" }
]
