name = "byjohann-link"
main = "./.output/server/index.mjs"
workers_dev = false
compatibility_date = "2023-06-13"

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

kv_namespaces = [
  { binding = "__BYJOHANN_LINK", id = "c80ecbb77b504762998f1286483c1230" }
]

[site]
bucket = ".output/public"
